spring.application.name=capacity_microservice
server.port=9091

# Configuración de la base de datos
spring.r2dbc.username=root
spring.r2dbc.password=l1109660212j
spring.r2dbc.url=r2dbc:mysql://localhost:3306/capacityMicroservice
spring.sql.init.mode=always

logging.level.org.springframework.r2dbc= DEBUG